// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwg3TGKDcFptAhq7WDkZAvhMEGMwUAz38',
    appId: '1:193799193857:web:65bb2f7dbca150063a8700',
    messagingSenderId: '193799193857',
    projectId: 'qandaupvote-6ecc3',
    authDomain: 'qandaupvote-6ecc3.firebaseapp.com',
    storageBucket: 'qandaupvote-6ecc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXSsDT_X78j95K16ossbEPh7ZC9CK-22k',
    appId: '1:193799193857:android:1a4da6e5957be50f3a8700',
    messagingSenderId: '193799193857',
    projectId: 'qandaupvote-6ecc3',
    storageBucket: 'qandaupvote-6ecc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3P5cwL9NjuNAyhGArMFqobpy6noeTP0Q',
    appId: '1:193799193857:ios:5bbf53527b306c603a8700',
    messagingSenderId: '193799193857',
    projectId: 'qandaupvote-6ecc3',
    storageBucket: 'qandaupvote-6ecc3.appspot.com',
    iosClientId: '193799193857-s839hm1smgebo9knd3acqfgusfhtttlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.qandaupvote',
  );
}
